// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
function getPublicClient() {
  const env = globalThis.process?.env ?? {};
  const url = env.SUPABASE_URL;
  const key = env.SUPABASE_PUBLISHABLE_KEY ?? env.SUPABASE_ANON_KEY;
  if (!url || !key) throw new Error("Supabase env not configured");
  return createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
}

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search ARIS Stationeries products by name, description, or category. Returns matching products with price, stock, slug, and image.",
  inputSchema: {
    query: z.string().optional().describe("Free-text search across name and description"),
    category: z.string().optional().describe("Filter by exact category name"),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }) => {
    const supabase = getPublicClient();
    let q = supabase.from("products").select("id, name, slug, price, original_price, category, image, stock, description, is_featured").order("is_featured", { ascending: false }).order("display_order", { ascending: true }).limit(limit ?? 20);
    if (query) q = q.or(`name.ilike.%${query}%,description.ilike.%${query}%`);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Fetch a single ARIS Stationeries product by slug, including variants and media.",
  inputSchema: {
    slug: z2.string().min(1).describe("Product slug from the URL, e.g. 'kiwi-shoe-polish'")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = getPublicClient();
    const { data: product, error } = await supabase.from("products").select("*").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!product) return { content: [{ type: "text", text: `No product with slug '${slug}'` }], isError: true };
    const [{ data: variants }, { data: media }] = await Promise.all([
      supabase.from("product_variants").select("*").eq("product_id", product.id),
      supabase.from("product_media").select("*").eq("product_id", product.id).order("display_order")
    ]);
    const payload = { product, variants: variants ?? [], media: media ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List all active product categories at ARIS Stationeries.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = getPublicClient();
    const { data, error } = await supabase.from("product_categories").select("id, name, slug, display_order").order("display_order");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-deals.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_deals_default = defineTool4({
  name: "list_deals",
  title: "List active deals",
  description: "List active flash sales, bundles, and BOGO (buy-one-get-one) offers at ARIS Stationeries.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = getPublicClient();
    const now = (/* @__PURE__ */ new Date()).toISOString();
    const [flash, bundles, bogo] = await Promise.all([
      supabase.from("products").select("id, name, slug, price, original_price, sale_ends_at").not("sale_ends_at", "is", null).gte("sale_ends_at", now),
      supabase.from("bundles").select("*").eq("is_active", true),
      supabase.from("bogo_offers").select("*").eq("is_active", true)
    ]);
    const payload = {
      flash_sales: flash.data ?? [],
      bundles: bundles.data ?? [],
      bogo_offers: bogo.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-testimonials.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_testimonials_default = defineTool5({
  name: "list_testimonials",
  title: "List customer testimonials",
  description: "List approved customer testimonials and reviews for ARIS Stationeries, ranked by rating.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max results (default 10)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = getPublicClient();
    const { data, error } = await supabase.from("customer_testimonials").select("id, customer_name, rating, review_text, image_url, created_at, product_id").eq("is_approved", true).order("rating", { ascending: false }).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { testimonials: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "aris-stationeries-mcp",
  title: "ARIS Stationeries",
  version: "0.1.0",
  instructions: "Browse the ARIS Stationeries catalog: search products, look up a product by slug, list categories, view active deals (flash sales, bundles, BOGO), and read customer testimonials. All tools are read-only and reflect the live storefront at arisstationaries.co.ke.",
  tools: [search_products_default, get_product_default, list_categories_default, list_deals_default, list_testimonials_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
